### ISSUE TITLE
telemtry only to see on miner?

### ISSUE THREAD

**Issue by gellfuen** [funakoshi2718/funakoshi-miner#32]
Hello!
Maybe I don't understand for what telemtry is used but if it is only bound to 127.0.0.1 I will not be able to see the data on a different computer. So why I can only see it on the miner?
b.t.w can you please add the temperatur of the GPU's and the runtime?
regards

**Comment by funakoshi2718** [comment]
You can access the miner's telemetry from remote browser, when your firewall settings permits it.

For security reasons it is prefered to use ssl-tunnel for accessing remotely instead of configuring
to firewall to allow remote access.

No permission is required when accessing the miner from a local browser.
